# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_examresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresult',
            options={'verbose_name': '\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442 \u0456\u0441\u043f\u0438\u0442\u0443', 'verbose_name_plural': '\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u0438 \u0456\u0441\u043f\u0438\u0442\u0456\u0432'},
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='student',
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Student'),
        ),
    ]
